# Generated by Django 4.1.6 on 2023-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
